// NOTE: This file is part of the DryWellSuite/OpenHydroQual codebase.
#ifndef DryWellDialog_H
#define DryWellDialog_H

#include <QDialog>
#include "scad_generator.h"

/**
 * @brief Structure containing all geometric parameters for the dry well model.
 *
 * This struct stores the full set of user-configurable geometry parameters
 * including pond dimensions, well properties, layering, hydraulic factors,
 * and elevations. These values are passed to the SCAD generator and VTK
 * visualization modules.
 */
struct GeomParams
{
    double pond_alpha_param = 86.061;      ///< Shape parameter α for pond geometry.
    double pond_beta_param  = 2.766;       ///< Shape parameter β for pond geometry.
    double pond_radius      = 6;           ///< Pond top radius (m).
    double well_radious     = 0.381;       ///< Well radius (m).
    unsigned int nr         = 10;          ///< Number of radial subdivisions.
    unsigned int n_layers   = 1;           ///< Number of vertical soil layers.
    double well_depth       = 20;          ///< Total depth of the well (m).
    double depth_to_gw      = 25.9;        ///< Initial depth to groundwater (m).
    double pond_initial_depth = 0;         ///< Initial pond water depth (m).
    double settlingchamberdepth     = 7.3; ///< Depth of main settling chamber (m).
    double side_settlingchamberdepth = 7.3;///< Depth of secondary chamber (m).
    unsigned int n_layer_deep = 1;         ///< Number of deeper layers.
    double Ks_factor        = 1;           ///< Scaling factor for Ks conductivity.
    double dr_increase_factor = 1.2;       ///< Radial grid expansion factor.
    bool log_dr_increase    = false;       ///< Use logarithmic spacing for Δr.
    double pipe_top         = -4.672584;   ///< Elevation of pipe top (m).
    double pipe_bottom      = -19;         ///< Elevation of pipe bottom (m).
    double surface_elevation = 140;        ///< Ground surface elevation (m).
};

QT_BEGIN_NAMESPACE
namespace Ui { class DryWellDialog; }
QT_END_NAMESPACE

/**
 * @class DryWellDialog
 * @brief Main GUI window for Dry Well model configuration and generation.
 *
 * This dialog provides the user interface for:
 *  - Loading soil layer data
 *  - Configuring well and pond geometry
 *  - Running the SCAD model generator
 *  - Exporting CAD drawings
 *  - Creating VTK visualizations
 *
 * It manages all user interactions, stores geometry settings through
 * GeomParams, and interfaces with @c SCAD_Generator and optional VTK routines.
 */
class DryWellDialog : public QDialog
{
    Q_OBJECT

public:
    enum class StructureVariant {
        DrywellSuite,
        VNDrywell
    };

    /**
     * @brief Construct the DryWellDialog.
     * @param parent Parent QWidget.
     */
    explicit DryWellDialog(QWidget *parent = nullptr,
                           StructureVariant variant = StructureVariant::DrywellSuite);

    /**
     * @brief Destructor.
     */
    ~DryWellDialog();

    GeomParams GP;  ///< Geometric parameters for the model.

private:
    Ui::DryWellDialog *ui; ///< UI object generated by Qt Designer.
    StructureVariant structureVariant = StructureVariant::DrywellSuite;
    QList<QStringList> LayerData; ///< Parsed soil layering information.
    bool uniform = true; ///< Flag indicating whether layers have uniform Ks.
    SCAD_Generator scad; ///< CAD model generator.
    bool freecad = true; ///< If true, output uses FreeCAD format.

private slots:
    /**
     * @brief Generate full SCAD model using current parameters.
     */
    void On_Generate_Model();

    /**
     * @brief Open file selection dialog for layer input.
     */
    void On_File_Select();

    /**
     * @brief Read soil layer CSV/text file and populate UI.
     */
    void On_ReadLayer_Info();

    /**
     * @brief Generate a CAD drawing using SCAD_Generator.
     */
    void On_CreateCADDrawing();

    /**
     * @brief Create VTK visualization of the generated geometry.
     */
    void On_CreateVTK();
};

#endif // DryWellDialog_H
